/*1360076899,178130529*/

if (self.CavalryLogger) { CavalryLogger.start_js(["OK6KH"]); }

__d("curry",["bind"],function(a,b,c,d,e,f){var g=b('bind'),h=g(null,g,null);e.exports=h;});
__d("PluginRecommendationsBar",["function-extensions","Event","Arbiter","CSS","DOM","Form","Plugin","PluginConnection","PluginPerms","PluginResize","UnverifiedXD","copyProperties","curry"],function(a,b,c,d,e,f){b('function-extensions');var g=b('Event'),h=b('Arbiter'),i=b('CSS'),j=b('DOM'),k=b('Form'),l=b('Plugin'),m=b('PluginConnection'),n=b('PluginPerms'),o=b('PluginResize'),p=b('UnverifiedXD'),q=b('copyProperties'),r=b('curry');function s(){}s.ACTION='Connect.Unsafe.platform/plugins/recommendations_bar/action';s.TRIGGER='Connect.Unsafe.platform/plugins/recommendations_bar/trigger';s.CREATE_READ='platform/plugins/recommendations_bar/create_read';s.DELETE_READ='platform/plugins/recommendations_bar/delete_read';s.OPEN='platform/plugins/recommendations_bar/open';function t(v){var w=function(){w=bagof(v());};return function(){return w();};}var u=[s.ACTION,s.TRIGGER];q(s.prototype,{init:function(v,w){this.element=v;var x=new o(function(){return w.offsetWidth+2;},function(){return v.offsetHeight;});x.resize().auto();this.resizer=x;h.registerCallback(r(h.inform,s.OPEN),u);h.subscribe(s.OPEN,function(){i.addClass(v,'pluginRecommendationsBarOpen');p.send({type:'signal_animation'});x.resize();});},initReadToggle:function(v,w,x,y,z,aa){g.listen(x,'click',r(k.bootstrap,y.getRoot()));g.listen(x,'click',v.show.bind(v,z.id));g.listen(z,'click',r(k.bootstrap,aa.getRoot()));g.listen(z,'click',v.show.bind(v,x.id));},initPerms:function(v,w){g.listen(v,'click',n.starter('recommendations_bar',w,['publish_actions']));},initRead:function(v){h.subscribe(s.OPEN,t(r(k.bootstrap,v.getRoot())));},initOpenLog:function(v){h.subscribe(s.OPEN,t(r(k.bootstrap,v.getRoot())));},initRecommendation:function(v,w,x,y,z){var aa=t(r(k.bootstrap,v.getRoot()));h.subscribe(u,aa);g.listen(y,'click',aa);g.listen(y,'click',r(i.addClass,this.element,'pluginRecommendationsBarOpen'));g.listen(z,'click',function(event){if(x.showing()!=w){x.show(w);}else i.removeClass(this.element,'pluginRecommendationsBarOpen');this.resizer.resize();return true;}.bind(this));},initLike:function(v,w,x,y){var z=new m().init(v,w,'pluginRecommendationsBarButtonDepressed');g.listen(w,'click',function(event){k.bootstrap((z.connected()?y:x).getRoot());z.toggle();return true;});},initError:function(v,w){h.subscribe(l.ERROR,function(event,x){j.setContent(v,x.content);w.show(v.id);i.addClass(this.element,'pluginRecommendationsBarOpen');this.resizer.resize();}.bind(this));}});e.exports=s;});
__d("PluginStack",["CSS","DOMQuery","copyProperties","createArrayFrom"],function(a,b,c,d,e,f){var g=b('CSS'),h=b('DOMQuery'),i=b('copyProperties'),j=b('createArrayFrom');function k(l,m){this._container=l;this._showing=m;}i(k.prototype,{show:function(l){this.hideAll();g.show(h.find(this.container(),'#'+l));this._showing=l;return this;},hideAll:function(){this.children().forEach(g.hide,g);return this;},container:function(){return this._container;},children:function(){return j(this.container().childNodes);},showing:function(){return this._showing;}});e.exports=k;});
__d("legacy:PluginOptin-legacy",["Plugin","PluginOptin"],function(a,b,c,d){if(!a.Plugin||!a.Plugin.CONNECT)a.Plugin=b('Plugin');a.Plugin.Optin=b('PluginOptin');},3);
__d("legacy:PluginRecommendationsBar-legacy",["Plugin","PluginRecommendationsBar"],function(a,b,c,d){if(!a.Plugin||!a.Plugin.CONNECT)a.Plugin=b('Plugin');a.Plugin.RecommendationsBar=b('PluginRecommendationsBar');},3);
__d("legacy:PluginStack-legacy",["Plugin","PluginStack"],function(a,b,c,d){if(!a.Plugin||!a.Plugin.CONNECT)a.Plugin=b('Plugin');a.Plugin.Stack=b('PluginStack');},3);